spring:
  application:
    name: instagram-clone
  config:
    import: ./config.yaml
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    encoding:
      charset: utf-8
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    password: ${mail.password}
    username: ${mail.username}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    port: 587
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
file:
  upload:
    path: ${upload.profile-path}
    board-path: ${upload.board-path}
jwt:
  secret: ${jwt.config.secret}
  access-expiry: 1800000
  refresh-expiry: 1209600000


kakao:
  client-id: 10ab6132cea328fff0ba8a0412eedbf3
  redirect-uri: http://localhost:8080/api/kakao/callback
  client-secret: 6ADsTGbuBiBPqgoKGjw9FNXsDKKvyhjD


logging:
  level:
    com.project.instagramclone: DEBUG   # 내 프로젝트
    org.mybatis: DEBUG                   # MyBatis
#    java.sql: DEBUG                      # SQL 작성문
#    java.sql.ResultSet: DEBUG           # SQL 사용에 따른 결과
    root: info                           # 기본은 INFO
#    com.zaxxer.hikari: DEBUG            # MYSQL 연결상태
#   org.springframework.jdbc: DEBUG     # JDBC

# mybatis -> 우리나라는 정말 많이 사용
# 외국 jpa -> org.mybatis 가 되지 않고,
# java.sql
# java.sql.ResultSet 을 사용하게 된다.














