db:
  url: jdbc:mysql://localhost:3306/instagram_clone
  username: root
  password: tjee1234

upload:
  profile-path: C:/uploads/profile
  board-path: C:/uploads/board
mail:
  username: tjoeun.jr5@gmail.com
  password: chjk wemd eooc wflj
jwt:
  config:
    secret: springboard-jwt-secret-key-2026-change-this-please!!!


















